export const FETCH_VIDEOS 					= 'FETCH_VIDEOS';
export const FETCH_VIDEO_SUCCESS 			= 'FETCH_VIDEO_SUCCESS';
export const VIDEOS_IS_LOADING 				= 'VIDEOS_IS_LOADING';
export const FETCH_SINGLE_VIDEO 			= 'FETCH_SINGLE_VIDEO';
